//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class AAu_CaLamViec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AAu_CaLamViec()
        {
            this.AAu_ChamCongTongHop = new HashSet<AAu_ChamCongTongHop>();
        }
    
        public string MaCa { get; set; }
        public string TenCa { get; set; }
        public Nullable<System.DateTime> GioBatDau { get; set; }
        public Nullable<System.DateTime> GioKetThuc { get; set; }
        public Nullable<System.DateTime> GioBatDauVao { get; set; }
        public Nullable<System.DateTime> GioKetThucRa { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<double> TongGioLamViec { get; set; }
        public Nullable<int> Ca { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AAu_ChamCongTongHop> AAu_ChamCongTongHop { get; set; }
    }
}
