//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class AAu_GiangVien
    {
        public string MaNV { get; set; }
        public string MaGV { get; set; }
        public int MaCC { get; set; }
        public Nullable<bool> GVNoiBo { get; set; }
    }
}
