//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class AAu_ChamCongTongHop
    {
        public int Id { get; set; }
        public int MaChamCong { get; set; }
        public System.DateTime NgayChamCong { get; set; }
        public string MaCaLamViec { get; set; }
        public string MaHT { get; set; }
        public string MaNV { get; set; }
        public string TenNV { get; set; }
        public Nullable<System.DateTime> GioVao { get; set; }
        public Nullable<System.DateTime> GioRa { get; set; }
        public Nullable<int> DiTre { get; set; }
        public Nullable<int> VeSom { get; set; }
        public Nullable<int> TongGioDay { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string TenMayCC { get; set; }
    
        public virtual AAu_CaLamViec AAu_CaLamViec { get; set; }
        public virtual AAu_HinhThuc AAu_HinhThuc { get; set; }
    }
}
