//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALAMVIEC
    {
        public string MaCaLamViec { get; set; }
        public string TenCaLamViec { get; set; }
        public string GioVao { get; set; }
        public string GioRa { get; set; }
        public string GioTong { get; set; }
        public Nullable<int> CongTinh { get; set; }
        public string BatDauNghiTrua { get; set; }
        public string KetThucNghiTrua { get; set; }
        public string TongGioNghiTrua { get; set; }
        public string GioBatDauVao { get; set; }
        public string GioKetThucVao { get; set; }
        public string GioBatDauRa { get; set; }
        public string GioKetThucRa { get; set; }
        public Nullable<bool> XemTC1 { get; set; }
        public Nullable<bool> XemTC2 { get; set; }
        public Nullable<bool> CaDem { get; set; }
        public Nullable<bool> ChuNhatXemNgayThuong { get; set; }
        public Nullable<bool> LeXemNgayThuong { get; set; }
        public Nullable<int> ChoPhepTre { get; set; }
        public Nullable<int> ChoPhepSom { get; set; }
        public Nullable<int> KhongCoGioVao { get; set; }
        public Nullable<int> KhongCoGioRa { get; set; }
        public Nullable<bool> TCTruocGioLamViec { get; set; }
        public Nullable<bool> TCSauGioLamViec { get; set; }
        public Nullable<int> PhutTangCaTruoc { get; set; }
        public Nullable<int> PhutTangCaSau { get; set; }
        public Nullable<int> TongGioDatToiTCTruoc { get; set; }
        public Nullable<int> TongGioDatToiTCSau { get; set; }
        public Nullable<int> PhutTruTCTruoc { get; set; }
        public Nullable<int> PhutTruTCSau { get; set; }
        public Nullable<int> GioiHanTC1 { get; set; }
        public Nullable<int> GioiHanTC2 { get; set; }
        public Nullable<int> CongTC1 { get; set; }
        public Nullable<int> CongTC2 { get; set; }
        public Nullable<bool> ChoPhepSuDung { get; set; }
    }
}
