//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaLamViecNew
    {
        public string MaCaLamViec { get; set; }
        public string CaLamViec { get; set; }
        public Nullable<System.DateTime> GioVaoLamViec { get; set; }
        public Nullable<System.DateTime> GioKetThucLamViec { get; set; }
        public Nullable<System.DateTime> GioBatDauNghiTrua { get; set; }
        public Nullable<System.DateTime> GioKetThucNghiTrua { get; set; }
        public Nullable<double> TongGioNghiTrua { get; set; }
        public Nullable<double> TongGioTrongCaLamViec { get; set; }
        public Nullable<double> CongTinh { get; set; }
        public Nullable<System.DateTime> BatDauVao { get; set; }
        public Nullable<System.DateTime> KetThucVao { get; set; }
        public Nullable<System.DateTime> BatDauRa { get; set; }
        public Nullable<System.DateTime> KetThucRa { get; set; }
        public Nullable<int> KhongCoGioRa { get; set; }
        public Nullable<int> KhongCoGioVao { get; set; }
        public Nullable<bool> XemCaDem { get; set; }
        public Nullable<bool> TinhBuTru { get; set; }
        public Nullable<bool> TruGioDiTre { get; set; }
        public Nullable<bool> TruGioVeSom { get; set; }
        public Nullable<int> ChoPhepDiTre { get; set; }
        public Nullable<bool> BatDauTinhDiTre { get; set; }
        public Nullable<int> ChoPhepVeSom { get; set; }
        public Nullable<bool> BatDauTinhVeSom { get; set; }
        public Nullable<bool> XemCaNayLaTangCa { get; set; }
        public Nullable<int> TangCaMuc { get; set; }
        public Nullable<bool> XemCuoiTuanLaTangCa { get; set; }
        public Nullable<int> TangCaCuoiTuanMuc { get; set; }
        public Nullable<bool> XemNgayLeLaTangCa { get; set; }
        public Nullable<int> TangCaNgayLeMuc { get; set; }
        public Nullable<bool> TangCaTruocGioLamViec { get; set; }
        public Nullable<int> SoPhutTangCaTruocGioLamViec { get; set; }
        public Nullable<bool> TangCaSauGioLamViec { get; set; }
        public Nullable<int> SoPhutTangCaSauGioLamViec { get; set; }
        public Nullable<bool> TongGioLamDatDen { get; set; }
        public Nullable<int> SoPhutTongGioLamDatDen { get; set; }
        public Nullable<int> TangCaTruocGioLamViecDatDen { get; set; }
        public Nullable<int> PhutTruTangCaTruoc { get; set; }
        public Nullable<int> TangCaSauGioLamViecDatDen { get; set; }
        public Nullable<int> PhutTruTangCaSau { get; set; }
        public Nullable<int> GioiHanTangCa1 { get; set; }
        public Nullable<int> GioiHanTangCa2 { get; set; }
        public Nullable<int> GioiHanTangCa3 { get; set; }
        public Nullable<int> GioiHanTangCa4 { get; set; }
    }
}
