//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckInOut
    {
        public int ID { get; set; }
        public Nullable<int> MaChamCong { get; set; }
        public Nullable<System.DateTime> NgayCham { get; set; }
        public Nullable<System.DateTime> GioCham { get; set; }
        public string KieuCham { get; set; }
        public string NguonCham { get; set; }
        public Nullable<int> MaSoMay { get; set; }
        public string TenMay { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
