//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietLichTrinhCaLamViec
    {
        public int ID { get; set; }
        public string MaLichTrinhCaLamViec { get; set; }
        public string Thu { get; set; }
        public string CaThu1 { get; set; }
        public string CaThu2 { get; set; }
        public string CaThu3 { get; set; }
        public string CaThu4 { get; set; }
        public string CaThu5 { get; set; }
        public string CaThu6 { get; set; }
        public string CaThu7 { get; set; }
        public string CaThu8 { get; set; }
        public string CaThu9 { get; set; }
        public string CaThu10 { get; set; }
    
        public virtual LICHTRINHCHOCALAMVIEC LICHTRINHCHOCALAMVIEC { get; set; }
    }
}
