//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietCongTruLuong
    {
        public int IDChiTietCongTruLuong { get; set; }
        public Nullable<int> MaChamCong { get; set; }
        public Nullable<decimal> ChiTietPhuCapCom { get; set; }
        public Nullable<decimal> ChiTietPhuCapKhac { get; set; }
        public Nullable<decimal> ChiTietTamUngLuong { get; set; }
        public Nullable<decimal> ChiTietViPham { get; set; }
        public Nullable<decimal> ChiTietThuong { get; set; }
    }
}
