//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETTAMUNGLUONG
    {
        public int IDTamUngLuong { get; set; }
        public Nullable<int> MaChamCong { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public string LyDo { get; set; }
        public Nullable<System.DateTime> NgayTamUng { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
