//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHUCAPNHANVIEN
    {
        public int IDChiTietPhuCap { get; set; }
        public Nullable<int> MaChamCong { get; set; }
        public string MaPhuCap { get; set; }
        public string TenPhuCap { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string KyHieuPhuCap { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
