//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietThuongNhanVien
    {
        public int IDThuong { get; set; }
        public Nullable<int> MaChamCong { get; set; }
        public string Thuong { get; set; }
        public Nullable<decimal> TienThuong { get; set; }
        public Nullable<System.DateTime> NgayThuong { get; set; }
    }
}
