//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUCVUNHANVIEN
    {
        public string MaChucVuNhanVien { get; set; }
        public string TenChucVuNhanVien { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
    }
}
