//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Face
    {
        public int MaChamCong { get; set; }
        public Nullable<int> FaceID { get; set; }
        public string FaceTemplate { get; set; }
        public Nullable<int> ChieuDai { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
