//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUVUC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHUVUC()
        {
            this.CHUCVUs = new HashSet<CHUCVU>();
            this.NHANVIENs = new HashSet<NHANVIEN>();
            this.PHONGBANs = new HashSet<PHONGBAN>();
        }
    
        public string MaKhuVuc { get; set; }
        public string MaCongTy { get; set; }
        public string TenKhuVuc { get; set; }
        public string DiaChiKhuVuc { get; set; }
        public string NguoiLienHe { get; set; }
        public string DienThoaiLienHe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUCVU> CHUCVUs { get; set; }
        public virtual CONGTY CONGTY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHANVIEN> NHANVIENs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONGBAN> PHONGBANs { get; set; }
    }
}
