//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class KYHIEUCHAMCONG
    {
        public string MaKyHieu { get; set; }
        public string DiTre { get; set; }
        public string VeSom { get; set; }
        public string DungGio { get; set; }
        public string TangCa { get; set; }
        public string ThieuGioVao { get; set; }
        public string ThieuGioRa { get; set; }
        public string Vang { get; set; }
        public string ChuaXepCa { get; set; }
        public string PhepNam { get; set; }
        public string Le { get; set; }
        public string CongTac { get; set; }
        public string VeTre { get; set; }
        public string CuoiTuan { get; set; }
    }
}
