//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHTRINHVAORA
    {
        public string MaLichTrinhVaoRa { get; set; }
        public string TenLichTrinhVaoRa { get; set; }
        public Nullable<int> ChonLichTrinhVaoRa { get; set; }
        public Nullable<bool> MotLanChamCong { get; set; }
        public Nullable<bool> LoaiBoGio { get; set; }
        public Nullable<System.DateTime> TuGio { get; set; }
        public Nullable<System.DateTime> DenGio { get; set; }
        public Nullable<int> ThoiGianNhoNhat { get; set; }
        public Nullable<int> ThoiGianLonNhat { get; set; }
        public Nullable<int> KhoangCachGiuaHaiCapVaoRa { get; set; }
    }
}
