//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHTRINHCHOCALAMVIEC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LICHTRINHCHOCALAMVIEC()
        {
            this.ChiTietLichTrinhCaLamViecs = new HashSet<ChiTietLichTrinhCaLamViec>();
            this.NGAYs = new HashSet<NGAY>();
        }
    
        public string MaLichTrinhCaLamViec { get; set; }
        public string TenLichTrinhCaLamViec { get; set; }
        public Nullable<int> ChuKy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietLichTrinhCaLamViec> ChiTietLichTrinhCaLamViecs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGAY> NGAYs { get; set; }
    }
}
