//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maychu
    {
        public string ID { get; set; }
        public Nullable<int> Cong { get; set; }
        public string DiaChiIP { get; set; }
        public string TenMayChu { get; set; }
    }
}
