//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAYCHAMCONG
    {
        public string MaMCC { get; set; }
        public string TenMCC { get; set; }
        public Nullable<int> IDMCC { get; set; }
        public string KieuKetNoi { get; set; }
        public string DiaChiIP { get; set; }
        public Nullable<int> Port { get; set; }
        public Nullable<int> CongCOM { get; set; }
        public string TocDoTruyen { get; set; }
        public string DiaChiWeb { get; set; }
        public Nullable<System.DateTime> NgayDangKyTenMien { get; set; }
        public Nullable<bool> SuDungWeb { get; set; }
        public string Serial { get; set; }
        public string SoDangKy { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> TrangThaiMay { get; set; }
    }
}
