//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGAYLE
    {
        public string MaNgayLe { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string TenNgayLe { get; set; }
        public Nullable<double> CongTinh { get; set; }
        public Nullable<double> Gio { get; set; }
        public string GhiChu { get; set; }
        public Nullable<double> HeSo { get; set; }
        public Nullable<bool> XacNhan { get; set; }
    }
}
