//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDUNG
    {
        public string MaNguoiDung { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string TenDayDu { get; set; }
        public Nullable<bool> XacNhan { get; set; }
        public Nullable<bool> BanLamViecMenu { get; set; }
        public Nullable<bool> ChonDuLieuMenu { get; set; }
        public Nullable<bool> NhatKySuDungMenu { get; set; }
        public Nullable<bool> ThayDoiNguoiDungMenu { get; set; }
        public Nullable<bool> PhanQuyenMenu { get; set; }
        public Nullable<bool> DoiMatKhauMenu { get; set; }
        public Nullable<bool> TuyChonMenu { get; set; }
        public Nullable<bool> CaiDatThoiGianTaiDuLieuTuDongMenu { get; set; }
        public Nullable<bool> ChayNenMenu { get; set; }
        public Nullable<bool> XoaDuLieuChamCongMenu { get; set; }
        public Nullable<bool> DuLieuMenu { get; set; }
        public Nullable<bool> NgonNguMenu { get; set; }
        public Nullable<bool> SoDoQuanLyMenu { get; set; }
        public Nullable<bool> QuanLyNhanVienMenu { get; set; }
        public Nullable<bool> DanhSachNhanVienMenu { get; set; }
        public Nullable<bool> ChuyenNhanVienVaoPhongBanMenu { get; set; }
        public Nullable<bool> CapNhatNhanVienTuExcelMenu { get; set; }
        public Nullable<bool> DangKyMenu { get; set; }
        public Nullable<bool> DanhMucMenu { get; set; }
        public Nullable<bool> KhaiBaoMenu { get; set; }
        public Nullable<bool> SapXepLichTrinhChoNhanVienMenu { get; set; }
        public Nullable<bool> PhepNamMenu { get; set; }
        public Nullable<bool> NghiCheDoMenu { get; set; }
        public Nullable<bool> DiCongTacMenu { get; set; }
        public Nullable<bool> DangKyTangCaChoNhanVienMenu { get; set; }
        public Nullable<bool> ChonNgayCuoiTuanMenu { get; set; }
        public Nullable<bool> XuatFileTextMenu { get; set; }
        public Nullable<bool> SuaGioGocMenu { get; set; }
        public Nullable<bool> ThemGioMenu { get; set; }
        public Nullable<bool> KhaiBaoCacLoaiNghiVaKyHieuMenu { get; set; }
        public Nullable<bool> KhaiBaoVangChoNhanVienMenu { get; set; }
        public Nullable<bool> LuongCoBanMenu { get; set; }
        public Nullable<bool> PhuCapMenu { get; set; }
        public Nullable<bool> KhaiBaoPhuCapTamUngLuongChoNhanVienMenu { get; set; }
        public Nullable<bool> GioChamCongMenu { get; set; }
        public Nullable<bool> ACLogMenu { get; set; }
        public Nullable<bool> NhanVienHienHanhMenu { get; set; }
        public Nullable<bool> TinhCongVaLuongMenu { get; set; }
        public Nullable<bool> TaiDuLieuMenu { get; set; }
        public Nullable<bool> TaiNhanVienVeMayTinhMenu { get; set; }
        public Nullable<bool> TaiDuLieuChamCongMenu { get; set; }
        public Nullable<bool> TaiNhanVienLenMayChamCongMenu { get; set; }
        public Nullable<bool> KhaiBaoMayChamCongMenu { get; set; }
        public Nullable<bool> DangKyMayChamCongMenu { get; set; }
        public Nullable<bool> KetNoiNhieuMayMenu { get; set; }
        public Nullable<bool> DuLieuChamCongTuHDDMenu { get; set; }
        public Nullable<bool> LuuDuLieuTuDongKhiChamCongMenu { get; set; }
        public Nullable<bool> ThongTinMayChuMenu { get; set; }
        public Nullable<bool> DocThuMenu { get; set; }
        public Nullable<bool> HuongDanSuDungMenu { get; set; }
        public Nullable<bool> HoTroQuaInternetMenu { get; set; }
        public Nullable<bool> YKienPhanHoiMenu { get; set; }
        public Nullable<bool> ThongTinPhanMemMenu { get; set; }
        public Nullable<bool> CapNhatPhanMemMenu { get; set; }
        public Nullable<bool> NhanVienTool { get; set; }
        public Nullable<bool> GioChamCongTool { get; set; }
        public Nullable<bool> BaoCaoTool { get; set; }
        public Nullable<bool> CaLamViecTool { get; set; }
        public Nullable<bool> LichTrinhVaoRaTool { get; set; }
        public Nullable<bool> LichTrinhCaLamViecTool { get; set; }
        public Nullable<bool> GanCaChoNhanVienTool { get; set; }
        public Nullable<bool> MayChamCongTool { get; set; }
        public Nullable<bool> QuanLyMayChamCongTool { get; set; }
        public Nullable<bool> HoTroTool { get; set; }
    }
}
