//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien_Test_
    {
        public string MaNhanVien { get; set; }
        public string TenNhanVien { get; set; }
        public int MaChamCong { get; set; }
        public string TenChamCong { get; set; }
        public string MaThe { get; set; }
        public string UserPassWord { get; set; }
        public Nullable<int> PhanQuyen { get; set; }
        public string UserEnable { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<System.DateTime> NgayVaoLamViec { get; set; }
        public string ChucVu { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string NoiSinh { get; set; }
        public string LoaiNhanVien { get; set; }
        public Nullable<int> CMND { get; set; }
        public string DienThoaiLienHe { get; set; }
        public string Email { get; set; }
        public Nullable<double> NgayPhep { get; set; }
        public byte[] HinhAnh { get; set; }
        public Nullable<decimal> TienLuong { get; set; }
        public string DanToc { get; set; }
        public string QuocTich { get; set; }
        public string Skype { get; set; }
        public string Yahoo { get; set; }
        public string Facebook { get; set; }
        public string MaCongTy { get; set; }
        public string MaKhuVuc { get; set; }
        public string MaPhongBan { get; set; }
        public string MaChucVu { get; set; }
        public string PassWord { get; set; }
        public Nullable<bool> DangThamGiaBaoHiem { get; set; }
        public Nullable<bool> NghiViecTamThoi { get; set; }
        public Nullable<bool> TinhLuongTheo { get; set; }
        public Nullable<bool> SanPhamOrCongDoan { get; set; }
    }
}
