//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.CheckInOuts = new HashSet<CheckInOut>();
            this.KhaiBaoVangChoNhanViens = new HashSet<KhaiBaoVangChoNhanVien>();
            this.ChiTietDangKyTangCas = new HashSet<ChiTietDangKyTangCa>();
            this.ChiTietDiCongTacs = new HashSet<ChiTietDiCongTac>();
            this.CHITIETPHUCAPNHANVIENs = new HashSet<CHITIETPHUCAPNHANVIEN>();
            this.CHITIETTAMUNGLUONGs = new HashSet<CHITIETTAMUNGLUONG>();
            this.PHEPNAMs = new HashSet<PHEPNAM>();
        }
    
        public string MaNhanVien { get; set; }
        public string TenNhanVien { get; set; }
        public int MaChamCong { get; set; }
        public string TenChamCong { get; set; }
        public string MaThe { get; set; }
        public string UserPassWord { get; set; }
        public Nullable<int> PhanQuyen { get; set; }
        public string UserEnable { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<System.DateTime> NgayVaoLamViec { get; set; }
        public string ChucVu { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string NoiSinh { get; set; }
        public string LoaiNhanVien { get; set; }
        public Nullable<System.DateTime> NgayKyHopDong { get; set; }
        public Nullable<double> ThoiHanHopDong { get; set; }
        public Nullable<int> CMND { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public string NoiCap { get; set; }
        public string DienThoaiLienHe { get; set; }
        public string Email { get; set; }
        public Nullable<double> NgayPhep { get; set; }
        public byte[] HinhAnh { get; set; }
        public Nullable<decimal> TienLuong { get; set; }
        public Nullable<decimal> LuongHopDong { get; set; }
        public string DanToc { get; set; }
        public string QuocTich { get; set; }
        public string TrinhDo { get; set; }
        public string Skype { get; set; }
        public string Yahoo { get; set; }
        public string Facebook { get; set; }
        public string MaCongTy { get; set; }
        public string MaKhuVuc { get; set; }
        public string MaPhongBan { get; set; }
        public string MaChucVu { get; set; }
        public string PassWord { get; set; }
        public Nullable<bool> DangThamGiaBaoHiem { get; set; }
        public Nullable<bool> NghiViecTamThoi { get; set; }
        public Nullable<bool> TinhLuongTheo { get; set; }
        public Nullable<bool> SanPhamOrCongDoan { get; set; }
        public Nullable<bool> NhanVienMoi { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> isDVP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckInOut> CheckInOuts { get; set; }
        public virtual CHUCVU CHUCVU1 { get; set; }
        public virtual CONGTY CONGTY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhaiBaoVangChoNhanVien> KhaiBaoVangChoNhanViens { get; set; }
        public virtual KHUVUC KHUVUC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDangKyTangCa> ChiTietDangKyTangCas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDiCongTac> ChiTietDiCongTacs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHUCAPNHANVIEN> CHITIETPHUCAPNHANVIENs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETTAMUNGLUONG> CHITIETTAMUNGLUONGs { get; set; }
        public virtual Face Face { get; set; }
        public virtual PHONGBAN PHONGBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHEPNAM> PHEPNAMs { get; set; }
    }
}
