//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanTheoGio
    {
        public int ID { get; set; }
        public string MaLichTrinhVaoRa { get; set; }
        public string TenLichTrinhVaoRa { get; set; }
        public Nullable<System.DateTime> BatDauVao { get; set; }
        public Nullable<System.DateTime> KetThucVao { get; set; }
        public Nullable<System.DateTime> BatDauRa { get; set; }
        public Nullable<System.DateTime> KetThucRa { get; set; }
    }
}
