//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHEPNAM
    {
        public int ID { get; set; }
        public string MaNhanVien { get; set; }
        public string TenNhanVien { get; set; }
        public int MaChamCong { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string DemCong { get; set; }
        public Nullable<int> DemGio { get; set; }
        public Nullable<double> Nghi { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
