//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHUCAP
    {
        public string MaPhuCap { get; set; }
        public string TenPhuCap { get; set; }
        public Nullable<decimal> SoTienPhuCap { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> SuDung { get; set; }
        public string KyHieuPhuCap { get; set; }
    }
}
