//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinhCong
    {
        public int ID { get; set; }
        public string MaNhanVien { get; set; }
        public string TenNhanVien { get; set; }
        public Nullable<int> MaChamCong { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string Thu { get; set; }
        public string Ca { get; set; }
        public string GioVao { get; set; }
        public string GioRa { get; set; }
        public string Cong { get; set; }
        public string Gio { get; set; }
        public Nullable<int> Tre { get; set; }
        public Nullable<int> VeSom { get; set; }
        public Nullable<int> VeTre { get; set; }
        public string TC1 { get; set; }
        public string TC2 { get; set; }
        public string TC3 { get; set; }
        public string TC4 { get; set; }
        public string TongGio { get; set; }
        public string DemCong { get; set; }
        public string KyHieu { get; set; }
        public string KyHieuPhu { get; set; }
        public string PhongBan { get; set; }
    }
}
