//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_IWVN
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUYCHON
    {
        public string MaTuyChinh { get; set; }
        public string ChuNhatHeSo { get; set; }
        public string ThuBayHeSo { get; set; }
        public string NgayLeHeSo { get; set; }
        public string CaDemHeSo { get; set; }
        public string TC1HeSo { get; set; }
        public string TC2HeSo { get; set; }
        public string TC3HeSo { get; set; }
        public string TC4HeSo { get; set; }
        public string GiamDoc { get; set; }
        public string KeToanTruong { get; set; }
        public string ThuQuy { get; set; }
        public string NguoiLapPhieu { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public string SoQuyetDinh { get; set; }
        public Nullable<System.DateTime> NgayApDung { get; set; }
        public string NguoiRaQuyetDinh { get; set; }
        public Nullable<int> LTTuA { get; set; }
        public Nullable<int> LTDenA { get; set; }
        public string LTA { get; set; }
        public Nullable<int> LTTuB { get; set; }
        public Nullable<int> LTDenB { get; set; }
        public string LTB { get; set; }
        public Nullable<int> LTTuC { get; set; }
        public Nullable<int> LTDenC { get; set; }
        public string LTC { get; set; }
        public Nullable<int> LTTuD { get; set; }
        public Nullable<int> LTDenD { get; set; }
        public string LTD { get; set; }
        public Nullable<int> LamTronCong { get; set; }
        public Nullable<int> LamTronGio { get; set; }
        public Nullable<double> BaoHiemXaHoi { get; set; }
        public Nullable<double> BaoHiemYTe { get; set; }
        public Nullable<double> BaoHiemThatNghiep { get; set; }
        public Nullable<bool> LuaChonKhaiBaoLuong { get; set; }
        public Nullable<decimal> SoTienKhaiBao { get; set; }
        public Nullable<decimal> TienTangCa { get; set; }
        public Nullable<bool> TienTheoNgayCong { get; set; }
        public Nullable<bool> TienTheoSanLuong { get; set; }
        public Nullable<decimal> TienSanLuong { get; set; }
        public Nullable<decimal> TienCongDoan { get; set; }
        public string DinhDangThoiGian { get; set; }
        public Nullable<int> ThongBaoHetHanHopDong { get; set; }
        public string DinhDangThoiGianHeThong { get; set; }
    }
}
